# Site settings
title: webaudiohackday.org
email: jan@krutisch.de
description: > # this means to ignore newlines until "baseurl:"
  A group of web audio enthusiasts running hackdays revolving
  around the web audio APIs in modern browsers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.webaudiohackday.org" # the base hostname & protocol for your site
twitter_username: webaudiohacks
github_username:  webaudiohackday

# Build settings
markdown: kramdown
collections:
  upcoming_hackdays:
    output: true
  past_hackdays:
    output: true
